local map = vim.keymap.set

map({ "n", "x" }, "<Space>", "<Nop>", { silent = true })
map("n", "<Esc>", "<cmd>nohlsearch<cr>", { desc = "Clear search highlight" })
map("n", "[q", "<cmd>cprevious<cr>", { desc = "Previous quickfix item" })
map("n", "]q", "<cmd>cnext<cr>", { desc = "Next quickfix item" })
map("n", "[l", "<cmd>lprevious<cr>", { desc = "Previous location item" })
map("n", "]l", "<cmd>lnext<cr>", { desc = "Next location item" })
map("n", "<leader>ff", function() require("fzf-lua").files() end, { desc = "Find files" })
map("n", "<leader>fg", function() require("fzf-lua").live_grep() end, { desc = "Live grep" })
map("n", "<leader>fb", function() require("cccvno1.core.buffers").find() end, { desc = "Find buffers" })
map("n", "<leader>fe", "<cmd>Oil<cr>", { desc = "File explorer" })
map("n", "<leader>sr", "<cmd>GrugFar<cr>", { desc = "Search and replace" })
map("n", "<leader>bd", function() require("cccvno1.core.buffers").close() end, { desc = "Close buffer" })
map("n", "<leader>bo", function() require("cccvno1.core.buffers").close_others() end, { desc = "Close other buffers" })
map("n", "<leader>bp", function() require("cccvno1.core.buffers").pin() end, { desc = "Pin buffer" })
map({ "n", "x", "o" }, "s", function() require("flash").jump() end, { desc = "Flash jump" })
map("n", "<leader>ww", "<cmd>write<cr>", { desc = "Write file" })
map("n", "<leader>qq", "<cmd>quit<cr>", { desc = "Quit window" })
map("n", "<leader>gg", "<cmd>DiffviewOpen<cr>", { desc = "Diffview" })
map("n", "<leader>gq", "<cmd>DiffviewClose<cr>", { desc = "Close Diffview" })
map("n", "<leader>gr", function() require("cccvno1.integrations.ws").git_review() end, { desc = "AI git review" })
map("n", "<leader>xx", "<cmd>Trouble diagnostics toggle<cr>", { desc = "Diagnostics" })
map("n", "<leader>xq", "<cmd>Trouble qflist toggle<cr>", { desc = "Quickfix" })
map("n", "<leader>co", "<cmd>AerialToggle<cr>", { desc = "Outline" })
map("n", "<leader>cf", function()
  require("lazy").load({ plugins = { "conform.nvim" } })
  require("conform").format({ async = true, lsp_format = "fallback" })
end, { desc = "Format buffer" })
map("n", "<leader>ul", function()
  vim.opt_local.list = not vim.opt_local.list:get()
end, { desc = "Toggle list chars" })
map("n", "<leader>uf", function()
  vim.b.autoformat = vim.b.autoformat == false
  vim.notify("Autoformat " .. (vim.b.autoformat and "enabled" or "disabled"))
end, { desc = "Toggle autoformat" })
map("n", "<leader>ud", function()
  local enabled = vim.diagnostic.is_enabled({ bufnr = 0 })
  vim.diagnostic.enable(not enabled, { bufnr = 0 })
  vim.notify("Diagnostics " .. (enabled and "disabled" or "enabled"))
end, { desc = "Toggle diagnostics" })
map("n", "<leader>ur", function()
  vim.opt_local.relativenumber = not vim.opt_local.relativenumber:get()
end, { desc = "Toggle relative number" })
map("n", "<leader>uw", function()
  vim.opt_local.wrap = not vim.opt_local.wrap:get()
end, { desc = "Toggle wrap" })
map("n", "<leader>ar", "<cmd>Sidekick cli send prompt=review_pack<cr>", { desc = "AI review pack" })
map("n", "<leader>ad", "<cmd>Sidekick cli send prompt=debug_pack<cr>", { desc = "AI debug pack" })
map("v", "<leader>aa", '<cmd>Sidekick cli send msg="{selection}"<cr>', { desc = "AI selection" })
map("v", "<leader>as", function() require("cccvno1.integrations.ws").selection() end, { desc = "Send selection to agent" })
map("n", "<leader>ax", function() require("cccvno1.integrations.ws").diagnostics() end, { desc = "Send diagnostics to agent" })
map("n", "<leader>aq", function() require("cccvno1.integrations.ws").quickfix() end, { desc = "Send quickfix to agent" })
map("n", "<leader>mp", "<cmd>LivePreviewToggle<cr>", { desc = "Markdown preview" })
