local map = vim.keymap.set

map({ "n", "x" }, "<Space>", "<Nop>", { silent = true })
map("n", "<Esc>", "<cmd>nohlsearch<cr>", { desc = "Clear search highlight" })
map("n", "[q", "<cmd>cprevious<cr>", { desc = "Previous quickfix item" })
map("n", "]q", "<cmd>cnext<cr>", { desc = "Next quickfix item" })
map("n", "[l", "<cmd>lprevious<cr>", { desc = "Previous location item" })
map("n", "]l", "<cmd>lnext<cr>", { desc = "Next location item" })
map("n", "<leader>ff", function() require("fzf-lua").files() end, { desc = "Find files" })
map("n", "<leader>fg", function() require("fzf-lua").live_grep() end, { desc = "Live grep" })
map("n", "<leader>fb", function() require("ad.core.buffers").find() end, { desc = "Find buffers" })
map("n", "<leader>e", "<cmd>Oil<cr>", { desc = "Open Oil" })
map("n", "<leader>sr", "<cmd>GrugFar<cr>", { desc = "Search and replace" })
map("n", "<leader>bd", function() require("ad.core.buffers").close() end, { desc = "Close buffer" })
map("n", "<leader>bo", function() require("ad.core.buffers").close_others() end, { desc = "Close other buffers" })
map("n", "<leader>bp", function() require("ad.core.buffers").pin() end, { desc = "Pin buffer" })
map({ "n", "x", "o" }, "s", function() require("flash").jump() end, { desc = "Flash jump" })
map("n", "<leader>gg", "<cmd>Neogit<cr>", { desc = "Neogit" })
map("n", "<leader>gd", "<cmd>CodeDiff<cr>", { desc = "Code diff" })
map("n", "<leader>xx", "<cmd>Trouble diagnostics toggle<cr>", { desc = "Diagnostics" })
map("n", "<leader>xq", "<cmd>Trouble qflist toggle<cr>", { desc = "Quickfix" })
map("n", "<leader>o", "<cmd>AerialToggle<cr>", { desc = "Outline" })
map("n", "<leader>ar", "<cmd>Sidekick cli send prompt=review_pack<cr>", { desc = "AI review pack" })
map("n", "<leader>ad", "<cmd>Sidekick cli send prompt=debug_pack<cr>", { desc = "AI debug pack" })
map("v", "<leader>aa", '<cmd>Sidekick cli send msg="{selection}"<cr>', { desc = "AI selection" })
map("n", "<leader>mp", "<cmd>LivePreviewToggle<cr>", { desc = "Markdown preview" })
